#!/bin/bash

echo "Running the Emscripten compiler..."
em++ src/wasm/*.cpp src/wasm/algorithms/*.cpp src/wasm/generators/*.cpp -o src/graph.js \
    -s WASM=1 \
    -I./src/wasm -I./src/wasm/igraph/build/include -I./src/wasm/igraph/include \
    -s EXPORT_ES6=1 \
    -s MODULARIZE=1 \
    -s ENVIRONMENT='web' \
    -s EXPORT_NAME='createModule' \
    -s LINKABLE=1 \
    -s FORCE_FILESYSTEM=1 \
    -s WASMFS=1 \
    -s EXPORTED_RUNTIME_METHODS=['FS'] \
    -lembind --no-entry \
    -Os \
    ./src/wasm/igraph/build/src/libigraph.a \
    && echo "Finished with no errors!"
